# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimpleWarzoneStatsTracker.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(467, 701)
        MainWindow.setMinimumSize(QtCore.QSize(467, 701))
        MainWindow.setMaximumSize(QtCore.QSize(467, 701))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/gas-mask.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QWidget#centralwidget{\n"
"border-image: url(:/img/img/26293.jpg);\n"
"}\n"
"\n"
"QFrame{\n"
"border-radius:15px;\n"
"background:#000029;\n"
"}\n"
"\n"
"QLabel#title{\n"
"font-family: ARMY RUST;\n"
"font-size:45px;\n"
"color:white;\n"
"}\n"
"\n"
"QLabel#profile{\n"
"font-family: Capture It;\n"
"font-size:20px;\n"
"color:white;\n"
"}\n"
"\n"
"QLabel#platform{\n"
"font-family: Capture It;\n"
"font-size:20px;\n"
"color:white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"border-radius:3px;\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton{\n"
"font-family: Capture It;\n"
"background-color: #001854;\n"
"border-radius:5px;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"font-family: Capture It;\n"
"background-color: #001039;\n"
"border-radius:5px;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"color:white;\n"
"}\n"
"\n"
"QTextEdit#warzone{\n"
"color:#1ccd00;\n"
"}\n"
"\n"
"QTextEdit#warzone_wins{\n"
"color:#c1cd00;\n"
"font-size:24px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QTextEdit#plunder{\n"
"color:#1ccd00;\n"
"}\n"
"\n"
"QTextEdit#plunder_wins{\n"
"color:#c1cd00;\n"
"font-size:24px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QTextEdit#all{\n"
"color:#1ccd00;\n"
"}\n"
"\n"
"QTextEdit#all_wins{\n"
"color:#c1cd00;\n"
"font-size:24px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QGroupBox{\n"
"font-family: Capture It;\n"
"color:white;\n"
" border: 1px solid gray;\n"
" border-color: #FF17365D;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setGeometry(QtCore.QRect(90, 30, 281, 41))
        self.title.setObjectName("title")
        self.gametag = QtWidgets.QLineEdit(self.frame)
        self.gametag.setGeometry(QtCore.QRect(120, 199, 301, 21))
        self.gametag.setText("")
        self.gametag.setObjectName("gametag")
        self.profile = QtWidgets.QLabel(self.frame)
        self.profile.setGeometry(QtCore.QRect(20, 200, 91, 16))
        self.profile.setObjectName("profile")
        self.platform = QtWidgets.QLabel(self.frame)
        self.platform.setGeometry(QtCore.QRect(20, 90, 121, 16))
        self.platform.setObjectName("platform")
        self.battle = QtWidgets.QPushButton(self.frame)
        self.battle.setGeometry(QtCore.QRect(330, 120, 71, 61))
        self.battle.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/battle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.battle.setIcon(icon1)
        self.battle.setIconSize(QtCore.QSize(45, 45))
        self.battle.setObjectName("battle")
        self.psn = QtWidgets.QPushButton(self.frame)
        self.psn.setGeometry(QtCore.QRect(30, 120, 71, 61))
        self.psn.setStatusTip("")
        self.psn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/psn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.psn.setIcon(icon2)
        self.psn.setIconSize(QtCore.QSize(45, 45))
        self.psn.setObjectName("psn")
        self.xbox = QtWidgets.QPushButton(self.frame)
        self.xbox.setGeometry(QtCore.QRect(130, 120, 71, 61))
        self.xbox.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/xbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.xbox.setIcon(icon3)
        self.xbox.setIconSize(QtCore.QSize(45, 45))
        self.xbox.setObjectName("xbox")
        self.steam = QtWidgets.QPushButton(self.frame)
        self.steam.setGeometry(QtCore.QRect(230, 120, 71, 61))
        self.steam.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/img/steam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.steam.setIcon(icon4)
        self.steam.setIconSize(QtCore.QSize(45, 45))
        self.steam.setObjectName("steam")
        self.mask = QtWidgets.QLabel(self.frame)
        self.mask.setGeometry(QtCore.QRect(370, 10, 61, 71))
        self.mask.setText("")
        self.mask.setPixmap(QtGui.QPixmap(":/img/img/gas-mask.png"))
        self.mask.setObjectName("mask")
        self.mask2 = QtWidgets.QLabel(self.frame)
        self.mask2.setGeometry(QtCore.QRect(10, 10, 61, 71))
        self.mask2.setText("")
        self.mask2.setPixmap(QtGui.QPixmap(":/img/img/gas-mask.png"))
        self.mask2.setObjectName("mask2")
        self.warzone_stats = QtWidgets.QGroupBox(self.frame)
        self.warzone_stats.setGeometry(QtCore.QRect(20, 260, 401, 131))
        self.warzone_stats.setObjectName("warzone_stats")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.warzone_stats)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 19, 381, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.warzone = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.warzone.setReadOnly(True)
        self.warzone.setObjectName("warzone")
        self.horizontalLayout.addWidget(self.warzone)
        self.warzone_wins = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.warzone_wins.setReadOnly(True)
        self.warzone_wins.setObjectName("warzone_wins")
        self.horizontalLayout.addWidget(self.warzone_wins)
        self.search = QtWidgets.QPushButton(self.frame)
        self.search.setGeometry(QtCore.QRect(20, 230, 401, 23))
        self.search.setObjectName("search")
        self.plunder_stats = QtWidgets.QGroupBox(self.frame)
        self.plunder_stats.setGeometry(QtCore.QRect(20, 400, 401, 131))
        self.plunder_stats.setObjectName("plunder_stats")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.plunder_stats)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 381, 101))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plunder = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.plunder.setReadOnly(True)
        self.plunder.setObjectName("plunder")
        self.horizontalLayout_2.addWidget(self.plunder)
        self.plunder_wins = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.plunder_wins.setReadOnly(True)
        self.plunder_wins.setObjectName("plunder_wins")
        self.horizontalLayout_2.addWidget(self.plunder_wins)
        self.all_stats = QtWidgets.QGroupBox(self.frame)
        self.all_stats.setGeometry(QtCore.QRect(20, 540, 401, 141))
        self.all_stats.setObjectName("all_stats")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.all_stats)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(9, 19, 381, 111))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.all = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        self.all.setReadOnly(True)
        self.all.setObjectName("all")
        self.horizontalLayout_3.addWidget(self.all)
        self.all_wins = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        self.all_wins.setReadOnly(True)
        self.all_wins.setObjectName("all_wins")
        self.horizontalLayout_3.addWidget(self.all_wins)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Warzone Stats Tracker"))
        self.title.setText(_translate("MainWindow", "Warzone Stats"))
        self.gametag.setPlaceholderText(_translate("MainWindow", "Gametag"))
        self.profile.setText(_translate("MainWindow", "Profile:"))
        self.platform.setText(_translate("MainWindow", "Platform:"))
        self.battle.setToolTip(_translate("MainWindow", "Battle.net"))
        self.psn.setToolTip(_translate("MainWindow", "PlayStation"))
        self.xbox.setToolTip(_translate("MainWindow", "Xbox Live"))
        self.steam.setToolTip(_translate("MainWindow", "Steam"))
        self.warzone_stats.setTitle(_translate("MainWindow", "Warzone Stats"))
        self.warzone.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.warzone_wins.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:24px; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.search.setText(_translate("MainWindow", "Search Profile"))
        self.plunder_stats.setTitle(_translate("MainWindow", "Plunder Stats"))
        self.plunder.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.plunder_wins.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:24px; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.all_stats.setTitle(_translate("MainWindow", "All Stats"))
        self.all.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.all_wins.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:24px; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:24px;\"><br /></p></body></html>"))
import resources
